name: Create release

on:
    push:
        tags:
            - "v*.*.*"

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
                  fetch-depth: 0

            - name: Check Nixpkgs inputs
              uses: DeterminateSystems/flake-checker-action@main
              with:
                  fail-mode: true

            - name: Install Nix
              uses: DeterminateSystems/nix-installer-action@main

            - uses: DeterminateSystems/magic-nix-cache-action@main

            - name: Build dist
              run: |
                  nix develop --command \
                    just all

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      ./documents/_build/project_plan_template_docs.zip
                      ./example/_build/example_project_plan.zip
                      ./course_planning/_build/exports/*.*
